"""
Integration tests for seldon docs generate.
Requires Neo4j.
"""
import pytest
from pathlib import Path
from seldon.domain.loader import load_domain_config
from seldon.core.artifacts import create_artifact, create_link
from seldon.commands.docs import _generate_docs

pytestmark = pytest.mark.usefixtures("neo4j_available")

NEO4J_DB = "seldon-test"
RESEARCH_YAML = Path(__file__).parent.parent / "seldon" / "domain" / "research.yaml"


@pytest.fixture
def domain_config():
    return load_domain_config(RESEARCH_YAML)


def test_generate_creates_all_five_files(
    neo4j_driver, project_dir, domain_config, clean_test_db, tmp_path
):
    """docs generate produces all 5 expected files."""
    generated = _generate_docs(neo4j_driver, NEO4J_DB, domain_config, tmp_path / "docs")

    file_names = {Path(p).name for p in generated}
    assert "scripts_reference.md" in file_names
    assert "data_dictionary.md" in file_names
    assert "results_registry.md" in file_names
    assert "experiment_catalog.md" in file_names
    assert "reproduction_guide.md" in file_names


def test_generated_files_have_header_comment(
    neo4j_driver, project_dir, domain_config, clean_test_db, tmp_path
):
    """Each generated file starts with the 'do not edit' header."""
    out_dir = tmp_path / "docs"
    _generate_docs(neo4j_driver, NEO4J_DB, domain_config, out_dir)

    for md_file in out_dir.glob("*.md"):
        content = md_file.read_text()
        assert "Generated by `seldon docs generate`" in content
        assert "Do not edit manually" in content


def test_generate_results_registry_contains_artifact(
    neo4j_driver, project_dir, domain_config, clean_test_db, tmp_path
):
    """results_registry.md includes Result artifact name and value."""
    create_artifact(
        project_dir=project_dir, driver=neo4j_driver, database=NEO4J_DB,
        domain_config=domain_config, artifact_type="Result",
        properties={
            "name": "entropy_result",
            "value": 3.14,
            "units": "bits",
            "description": "entropy of system",
            "interpretation": "high entropy indicates diversity",
        },
        actor="human", authority="accepted",
    )

    out_dir = tmp_path / "docs"
    _generate_docs(neo4j_driver, NEO4J_DB, domain_config, out_dir)

    content = (out_dir / "results_registry.md").read_text()
    assert "entropy_result" in content
    assert "3.14" in content
    assert "bits" in content
    assert "high entropy indicates diversity" in content


def test_generate_scripts_reference_contains_artifact(
    neo4j_driver, project_dir, domain_config, clean_test_db, tmp_path
):
    """scripts_reference.md includes Script artifact."""
    create_artifact(
        project_dir=project_dir, driver=neo4j_driver, database=NEO4J_DB,
        domain_config=domain_config, artifact_type="Script",
        properties={
            "name": "run_experiment",
            "path": "src/run_experiment.py",
            "description": "Runs the main experiment",
            "usage": "python src/run_experiment.py --seed 42",
        },
        actor="human", authority="accepted",
    )

    out_dir = tmp_path / "docs"
    _generate_docs(neo4j_driver, NEO4J_DB, domain_config, out_dir)

    content = (out_dir / "scripts_reference.md").read_text()
    assert "run_experiment" in content
    assert "src/run_experiment.py" in content
    assert "Runs the main experiment" in content


def test_generate_empty_graph_produces_stub_content(
    neo4j_driver, project_dir, domain_config, clean_test_db, tmp_path
):
    """With no artifacts, generated files contain 'No X artifacts' stubs."""
    out_dir = tmp_path / "docs"
    _generate_docs(neo4j_driver, NEO4J_DB, domain_config, out_dir)

    assert "No Script artifacts in graph" in (out_dir / "scripts_reference.md").read_text()
    assert "No Result artifacts in graph" in (out_dir / "results_registry.md").read_text()
    assert "No DataFile artifacts in graph" in (out_dir / "data_dictionary.md").read_text()
    assert "No PipelineRun artifacts in graph" in (out_dir / "reproduction_guide.md").read_text()


def test_generate_experiment_catalog_links_results(
    neo4j_driver, project_dir, domain_config, clean_test_db, tmp_path
):
    """experiment_catalog.md shows Results generated by each Script."""
    script_id = create_artifact(
        project_dir=project_dir, driver=neo4j_driver, database=NEO4J_DB,
        domain_config=domain_config, artifact_type="Script",
        properties={"name": "compute_score", "path": "src/compute.py"},
        actor="human", authority="accepted",
    )
    result_id = create_artifact(
        project_dir=project_dir, driver=neo4j_driver, database=NEO4J_DB,
        domain_config=domain_config, artifact_type="Result",
        properties={"name": "final_score", "value": 0.95, "units": "acc", "description": "final"},
        actor="human", authority="accepted",
    )
    create_link(
        project_dir=project_dir, driver=neo4j_driver, database=NEO4J_DB,
        domain_config=domain_config,
        from_id=result_id, to_id=script_id,
        from_type="Result", to_type="Script",
        rel_type="generated_by", actor="human", authority="accepted",
    )

    out_dir = tmp_path / "docs"
    _generate_docs(neo4j_driver, NEO4J_DB, domain_config, out_dir)

    content = (out_dir / "experiment_catalog.md").read_text()
    assert "compute_score" in content
    assert "final_score" in content
    assert "0.95" in content
