"""CLI commands for project glossary management.

Provides:
  seldon glossary generate  -- render glossary.md from ontology term replicas

The glossary file is a generated projection of OntologyTerm artifacts in the
project database. Do not edit it directly — run `seldon glossary generate`
to regenerate after changing ontology terms via `seldon ontology ingest` +
`seldon ontology sync`.
"""

from __future__ import annotations

import os
from pathlib import Path
from typing import Optional

import click


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_GENERATED_HEADER = (
    "<!-- Generated by seldon glossary generate. Do not edit directly.\n"
    "     Source: ontology term replicas in project graph.\n"
    "     Regenerate: seldon glossary generate -->\n"
)


def _get_glossary_output_path(config: dict, project_dir: Path) -> Path:
    """Resolve glossary output path from seldon.yaml.

    Resolution order:
    1. paths.glossary (explicit override)
    2. paths.book / glossary.md
    3. paths.sections parent / glossary.md  (paper layout)
    4. Fallback: project_dir / glossary.md
    """
    paths = config.get("paths", {})

    if paths.get("glossary"):
        return project_dir / paths["glossary"]
    if paths.get("book"):
        return project_dir / paths["book"] / "glossary.md"
    if paths.get("sections"):
        sections_path = Path(paths["sections"])
        return project_dir / sections_path.parent / "glossary.md"

    return project_dir / "glossary.md"


def _render_glossary(terms: list[dict]) -> str:
    """Render a list of ontology term dicts as a MyST {glossary} directive.

    Terms are sorted case-insensitively by name. Each entry uses the standard
    MyST glossary format:

        term name
        : Definition text.

    Args:
        terms: List of OntologyTerm property dicts from Neo4j.

    Returns:
        Full glossary.md content string including header and directive.
    """
    sorted_terms = sorted(terms, key=lambda t: t.get("name", "").lower())

    lines = [
        _GENERATED_HEADER,
        "```{glossary}",
    ]

    for term in sorted_terms:
        name = term.get("name", "").strip()
        definition = term.get("definition", "").strip()
        if not name or not definition:
            continue
        lines.append(name)
        lines.append(f": {definition}")
        lines.append("")  # blank line between entries

    lines.append("```")
    lines.append("")  # trailing newline

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Click command group
# ---------------------------------------------------------------------------

@click.group("glossary")
def glossary_group():
    """Manage project glossary (generated from ontology)."""
    pass


@glossary_group.command("generate")
@click.option(
    "--output",
    default=None,
    help="Output path for glossary.md (default: derived from seldon.yaml paths).",
)
@click.option(
    "--dry-run",
    is_flag=True,
    help="Show what would be written without writing the file.",
)
def generate_command(output: Optional[str], dry_run: bool):
    """Generate glossary.md from OntologyTerm replicas in this project.

    Queries the project database for all active OntologyTerm artifacts and
    renders them in MyST {glossary} directive format. Overwrites the target
    file. Run `seldon ontology sync` first to ensure replicas are current.
    """
    from dotenv import load_dotenv
    from seldon.config import get_neo4j_driver, load_project_config

    project_dir = Path.cwd()
    load_dotenv(project_dir / ".env", override=False)

    config = load_project_config(project_dir)
    database = config["neo4j"]["database"]

    driver = get_neo4j_driver(config)
    try:
        with driver.session(database=database) as session:
            records = session.run(
                "MATCH (a:Artifact:OntologyTerm) "
                "WHERE a.state = 'active' "
                "RETURN a "
                "ORDER BY a.name"
            ).data()

        terms = [dict(r["a"]) for r in records]

        if not terms:
            raise click.ClickException(
                "No active OntologyTerm artifacts found in project database. "
                "Run `seldon ontology sync` to pull terms from master."
            )

    finally:
        driver.close()

    content = _render_glossary(terms)

    if output:
        out_path = Path(output)
    else:
        out_path = _get_glossary_output_path(config, project_dir)

    if dry_run:
        click.echo(f"[DRY RUN] Would write {len(terms)} terms to: {out_path}")
        click.echo(f"\n--- Preview (first 20 lines) ---")
        for line in content.splitlines()[:20]:
            click.echo(line)
        click.echo("---")
        click.echo("No file written.")
        return

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(content, encoding="utf-8")

    # Count by category for summary
    by_cat: dict[str, int] = {}
    for t in terms:
        cat = t.get("category", "unknown")
        by_cat[cat] = by_cat.get(cat, 0) + 1

    click.echo(f"Generated glossary: {out_path}")
    click.echo(f"  {len(terms)} terms written:")
    for cat in sorted(by_cat.keys()):
        click.echo(f"    {cat}: {by_cat[cat]}")
